Fixing some porting issues with ksh -> sh changes. Ensuring that txg is appropriately accounted for along with numbers. Fixed quoting, and formatting.

diff --git a/zilstat b/zilstat
--- a/zilstat
+++ b/zilstat
@@ -67,17 +67,49 @@ done
 
 shift $((OPTIND - 1))
 
+### option logic
+if [ "$1" = "txg" ] || [ "$1" -gt 0 ]; then
+	INTERVAL="$1"; 
+	shift
+fi
+
+if [ "$1" != "" ] && ( [ "$1" = "txg" ] || [ "$1" -gt 0 ] ) ; then
+	COUNT="$1";
+	shift
+fi
+
+if [ "$OPT_POOL" -eq 1 ]; then
+    FILTER=1
+fi
+
+case "$INTERVAL" in
+    "txg")
+        if [ "$OPT_POOL" -ne 1 ]; then
+            echo "error: -p poolname option must be used for txg intervals"
+            exit 1
+        fi
+        OPT_TXG=1
+        INTERVAL=0
+        ;;
+    [0-9]*)
+        ;;
+    *)  
+        echo "error: interval must be a number or \"txg\""
+        exit 1
+        ;;
+esac
+
 cat > $SCRIPT_PATH <<EOF
 	 #pragma D option quiet
 	 inline int OPT_TIME = $OPT_TIME;
-	 inline int OPT_TXG = $OPT_TXG;
+	 inline int OPT_TXG  = $OPT_TXG;
 	 inline int OPT_POOL = $OPT_POOL;
 	 inline int OPT_MEGA = $OPT_MEGA;
 	 inline int INTERVAL = $INTERVAL;
-	 inline int LINES = $LINES;
-	 inline int COUNTER = $COUNT;
-	 inline int FILTER = $FILTER;
-	 inline string POOL = "'$POOL'";
+	 inline int LINES    = $LINES;
+	 inline int COUNTER  = $COUNT;
+	 inline int FILTER   = $FILTER;
+	 inline string POOL  = "$POOL";
 	 dtrace:::BEGIN
 	 {
 		/* starting values */
